language: node_js
os:
  - linux
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  local_dir: dist
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
