language: node_js
os:
  - linux
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
deploy:
  edge: true
  keep_history: true
  local_dir: dist
  provider: pages
  repo: afiorenza.github.io
  target-branch: master
  token: $GITHUB_TOKEN
  on:
    branch: master
