language: node_js
os:
  - linux
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn build
# deploy:
#   keep_history: false
#   local_dir: dist
#   provider: pages
#   repo: afiorenza/afiorenza.github.io
#   skip_cleanup: true
#   target-branch: master
#   token: $GITHUB_TOKEN
#   on:
#     branch: master
